name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=catppuccin_mocha&border_radius=10.0&include_all_commits=true&border_color=c6a0f6
          path: profile/stats.svg
          token: ${{ secrets.READMEPAT }}
          
      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=8&theme=catppuccin_mocha&card_width=300&border_radius=10.0&border_color=c6a0f6&size_weight=0.5&count_weight=0.5
          path: profile/top-langs.svg
          token: ${{ secrets.READMEPAT }}

#      - name: Generate pin card
#        uses: readme-tools/github-readme-stats-action@v1
#        with:
#          card: pin
#          options: username=readme-tools&repo=github-readme-stats
#          path: profile/pin-readme-tools-github-readme-stats.svg
#          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate wakatime card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: username=__warden&layout=compact&theme=catppuccin_mocha&border_radius=10.0&border_color=c6a0f6
          path: profile/wakatime.svg
          token: ${{ secrets.READMEPAT }}
      
      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
